### ISSUE TITLE
CreateMixin should support additional status codes

### ISSUE THREAD

**Issue by ddobson** [Vacasa/drf-jsonapi#39]
**Is your feature request related to a problem? Please describe.**
According to the spec, the `POST /resource` endpoint should support configuration for 202 and 204 response codes.

https://jsonapi.org/format/#crud-creating-responses-202

**Describe the solution you'd like**
Add an `http_status` kwarg with 201 as a default status code. 

- **201:** Default option. Should function exactly the way it does now.
- **202:** This option implies that the request was accepted but that the resource has not yet been created. Respond to the client with 202 and end execution early (Do not perform the usual creation actions); additional functionality will need to come from the developer's implementation.
- **204**: Function should work exactly as it does today except that a response with 204 is returned and there is no document body.

**Comment by chrisbrantley** [comment]
@ddobson The default behavior is to return a `201` along with the newly created resource. This is ideal because the ID is usually generated dynamically and you need to return it with the response.

Supporting `202` or `204` can be done easily by overriding the ViewSet's `create` method to return the appropriate response. 

For example:

```
from rest_framework import status
from drf_jsonapi.response import Response

def create(self, request):
    default_response = super().create(request)
    return Response(status=status.HTTP_204_NO_CONTENT)
```

I'm not crazy about making it a simple setting because the status code you respond with is highly dependent on how the request is processed. We don't want to simply return a different status without handling the request according to the spec. For example, if you generate a dynamic ID or have any default values for any fields you don't want to return a 204.

Any other thoughts?

**Comment by ddobson** [comment]
> I'm not crazy about making it a simple setting because the status code you respond with is highly dependent on how the request is processed.

@chrisbrantley fair enough. This is especially true when responding with 202. Your solution is simple enough for the (most likely rare) cases when you don't want a 201. Closing this issue.
